//! The Fractal Audio's core protocol constants

pub const SYSEX_START: u8 = 0xF0;
pub const SYSEX_MANUFACTURER_BYTE1: u8 = 0x00;
pub const SYSEX_MANUFACTURER_BYTE2: u8 = 0x01;
pub const SYSEX_MANUFACTURER_BYTE3: u8 = 0x74;
pub const SYSEX_END: u8 = 0xF7;

pub const SYSEX_MANUFACTURER: [u8; 3] = [SYSEX_MANUFACTURER_BYTE1, SYSEX_MANUFACTURER_BYTE2, SYSEX_MANUFACTURER_BYTE3];
pub const SYSEX_HEADER: [u8; 4] = [SYSEX_START, SYSEX_MANUFACTURER_BYTE1, SYSEX_MANUFACTURER_BYTE2, SYSEX_MANUFACTURER_BYTE3];
