[package]
name = "frako"
version = "0.1.0"
authors = ["rudi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.6.2"
bus = "2.2.3"
