[package]
name = "fractal_protocol"
version = "0.1.0"
authors = ["rudi"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
packed_struct = "0.3"
packed_struct_codegen = "0.3"